overrides:
  vitest-environment-prisma: link:../../AppData/Local/pnpm/global/5/node_modules/vitest-environment-prisma
  vitest-environment-prisma-e2e: link:../../AppData/Local/pnpm/global/5/node_modules/vitest-environment-prisma-e2e
